# Generated by Django 2.2.10 on 2020-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navuser',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='navuser',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
